import asyncio

from src.agents.state import AgentState
from src.retrieval.retrieval_engine import retrieve


def retriever_node(state: AgentState) -> dict:
    """
    Retriever Agent — runs after the Planner.

    Calls the Phase 3 retrieval engine (hybrid BM25 + vector → rerank) once
    for each sub_question in the query plan, then merges all results into a
    single deduplicated list ranked by best score.

    Why one retrieval call per sub_question?
    A question like "Why did checkout fail after deployment?" has two distinct
    retrieval needs: (a) checkout errors and (b) deployment events. A single
    query would retrieve documents that score well for the combined text but
    miss documents that only match one aspect. Running separate queries and
    merging covers both needs.

    Why deduplicate by chunk_id?
    Multiple sub_questions can retrieve the same chunk. The same log line about
    the deployment start might be the best result for both "deployment at 16:00"
    and "checkout version change" queries. Without deduplication, the Reasoning
    Agent would see the same evidence multiple times and over-weight it.

    This node is synchronous (LangGraph nodes are sync by default).
    asyncio.run() is used to call the async retrieval_engine from sync context.
    """
    plan = state["query_plan"]

    # Pull filter fields from the plan
    services     = plan.get("services", [])
    time_range   = plan.get("time_range", {}) or {}
    severity     = plan.get("severity_filter", [])
    sub_questions = plan.get("sub_questions", [])

    # Also include any additional queries generated by the Reflection Agent on retry
    all_queries = sub_questions + state.get("additional_queries", [])

    service_name = services[0] if services else None
    start_time   = time_range.get("start")
    end_time     = time_range.get("end")

    seen_ids: set[str] = set()
    merged: list[dict] = []

    for query in all_queries:
        results = asyncio.run(
            retrieve(
                query=query,
                service_name=service_name,
                severity=severity if severity else None,
                start_time=start_time,
                end_time=end_time,
            )
        )
        for chunk in results:
            if chunk["chunk_id"] not in seen_ids:
                seen_ids.add(chunk["chunk_id"])
                merged.append(chunk)

    # Sort merged results by rerank_score descending (best evidence first)
    merged.sort(key=lambda c: c.get("rerank_score", 0), reverse=True)

    return {"retrieved_chunks": merged}
